# PRODUCTION DATABASE (Cloud Managed / AWS RDS)
spring.datasource.url=${PROD_DB_URL}
spring.datasource.username=${PROD_DB_USER}
spring.datasource.password=${PROD_DB_PASSWORD}

# JPA
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Disable local dev compose handlers
spring.docker.compose.enabled=false

# PRODUCTION FILE STORAGE
aws.s3.endpoint=${PROD_S3_URL}
aws.s3.access-key=${PROD_S3_ACCESS_KEY}
aws.s3.secret-key=${PROD_S3_SECRET_KEY}
aws.s3.region=${PROD_S3_REGION}
aws.s3.bucket=${PROD_S3_BUCKET}

# FRONTEND CORS CONNECTION
app.frontend.url=${PROD_FRONTEND_URL}

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false