create sequence semesters_seq
    increment by 50;

create table outbox_events
(
    id            bigint generated by default as identity
        primary key,
    created_at    timestamp(6),
    error_message text,
    event_type    varchar(255) not null,
    payload       text         not null,
    processed_at  timestamp(6),
    retry_count   integer      not null,
    status        varchar(255) not null
        constraint outbox_events_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[]))
);

create table semesters
(
    id                    bigint       not null
        primary key,
    created_at            timestamp(6),
    end_date              date         not null,
    enrollment_end_date   date,
    enrollment_start_date date,
    is_current            boolean      not null,
    name                  varchar(255) not null
        constraint ukci1s5s8npb7j044md3s0wdhsh
            unique
        constraint ukgvocevpk0hmp1h65pn9tnp4bu
            unique,
    start_date            date         not null
);

create table system_configuration
(
    id                      bigint not null
        primary key,
    allowed_student_domains text   not null
);

create table users
(
    role                varchar(31)  not null
        constraint users_role_check
            check ((role)::text = ANY
                   ((ARRAY ['ROLE_ADMIN'::character varying, 'ROLE_PROF'::character varying, 'ROLE_STUDENT'::character varying])::text[])),
    id                  bigint generated by default as identity
        primary key,
    created_at          timestamp(6),
    deactivated         boolean      not null,
    email               varchar(255) not null
        constraint uk6dotkott2kjsp8vw4d0m25fb7
            unique,
    first_name          varchar(255) not null,
    last_name           varchar(255) not null,
    password_hash       varchar(255) not null,
    phone               varchar(255),
    profile_picture_key varchar(255),
    university_id       varchar(255) not null
        constraint ukrebo2xbcgxy60wi2e79gd4o86
            unique
        constraint ukq4gvg4dl2a3fpetfwspodde8e
            unique
);

create table admins
(
    user_id bigint not null
        primary key
        constraint fkgc8dtql9mkq268detxiox7fpm
            references users
);

create table attachments
(
    id                 bigint generated by default as identity
        primary key,
    content_type       varchar(255) not null,
    created_at         timestamp(6),
    object_key         varchar(255) not null
        constraint ukhi2svrbqh5f5adklisy5imj8o
            unique
        constraint uk3bimcsnusdmmnmjgljymrwif6
            unique,
    original_file_name varchar(255) not null,
    size_in_bytes      bigint       not null,
    uploaded_by_id     bigint       not null
        constraint fktj5qjndi69v9hltsn7q7ddx8g
            references users
);

create table notifications
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6),
    is_read    boolean      not null,
    message    varchar(255) not null,
    target_url varchar(255) not null,
    user_id    bigint       not null
        constraint fk9y21adhxn0ayjhfocscqox7bh
            references users
);

create table professors
(
    department varchar(255),
    office     varchar(255),
    title      varchar(255),
    user_id    bigint not null
        primary key
        constraint fklq1bc4wecor3b2lr0whjiimy8
            references users
);

create table courses
(
    id                bigint generated by default as identity
        primary key,
    created_at        timestamp(6),
    credits           integer      not null
        constraint courses_credits_check
            check (credits >= 0),
    deactivated       boolean      not null,
    description       text,
    faculty           varchar(255) not null,
    title             varchar(255) not null,
    lead_professor_id bigint       not null
        constraint fk8mrg3j1806vpdnxktm23ld6km
            references professors,
    semester_id       bigint       not null
        constraint fklr7ck4w266my7691avtikan92
            references semesters
);

create table course_sections
(
    id        bigint generated by default as identity
        primary key,
    type      varchar(255) not null
        constraint course_sections_type_check
            check ((type)::text = ANY
                   ((ARRAY ['LECTURE'::character varying, 'LAB'::character varying, 'PRACTICAL'::character varying])::text[])),
    course_id bigint       not null
        constraint fk4xiaseygl0aodt5ahkbm8s2ds
            references courses
);

create table course_sessions
(
    id                bigint generated by default as identity
        primary key,
    business_key      varchar(255) not null
        constraint ukqwhmuybjywlu5teh6x856uq7q
            unique
        constraint ukp3uwbngqr8bnnhi2oo7q4srk2
            unique,
    day_of_week       varchar(255) not null
        constraint course_sessions_day_of_week_check
            check ((day_of_week)::text = ANY
                   ((ARRAY ['MONDAY'::character varying, 'TUESDAY'::character varying, 'WEDNESDAY'::character varying, 'THURSDAY'::character varying, 'FRIDAY'::character varying, 'SATURDAY'::character varying, 'SUNDAY'::character varying])::text[])),
    end_time          time(0)      not null,
    max_capacity      integer      not null
        constraint course_sessions_max_capacity_check
            check (max_capacity >= 0),
    name              varchar(255),
    room              varchar(255) not null,
    start_time        time(0)      not null,
    professor_id      bigint       not null
        constraint fkkm9cn02dwxfkon0gwxw3oka47
            references professors,
    course_section_id bigint       not null
        constraint fk7mgy4f7372wokqpiaaf8mviga
            references course_sections
);

create table posts
(
    post_type          varchar(31)  not null
        constraint posts_post_type_check
            check ((post_type)::text = ANY
                   ((ARRAY ['ANNOUNCEMENT'::character varying, 'ASSIGNMENT'::character varying, 'MATERIAL'::character varying, 'QUIZ'::character varying])::text[])),
    id                 bigint generated by default as identity
        primary key,
    body               text         not null,
    created_at         timestamp(6),
    title              varchar(255) not null,
    visibility         varchar(255) not null
        constraint posts_visibility_check
            check ((visibility)::text = ANY
                   ((ARRAY ['FACULTY_ONLY'::character varying, 'ENROLLED_ONLY'::character varying, 'PUBLIC'::character varying])::text[])),
    week               integer      not null,
    due_date           timestamp(6),
    max_points         integer
        constraint posts_max_points_check
            check (max_points >= 0),
    passing_score      integer,
    shuffle_questions  boolean,
    time_limit_minutes integer,
    author_id          bigint       not null
        constraint fk6xvn0811tkyo3nfjk2xvqx6ns
            references users,
    course_id          bigint       not null
        constraint fkm2hjujpdly9emepkb7cdi05t3
            references courses
);

create table comments
(
    id         bigint generated by default as identity
        primary key,
    body       text   not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    author_id  bigint not null
        constraint fkn2na60ukhs76ibtpt9burkm27
            references users,
    post_id    bigint not null
        constraint fkh4c7lvsc298whoyd4w9ta25cr
            references posts
);

create table post_attachments
(
    post_id       bigint not null
        constraint fkdwocy2l1nlf11ebpfrax6sto1
            references posts,
    attachment_id bigint not null
        constraint ukim4fulgfsrobi0ykmptbdarqx
            unique
        constraint fkks0cdnlpf3pwf77n3paobqhm3
            references attachments,
    primary key (post_id, attachment_id)
);

create table quiz_questions
(
    id      bigint generated by default as identity
        primary key,
    points  integer      not null
        constraint quiz_questions_points_check
            check (points >= 0),
    text    text         not null,
    type    varchar(255) not null
        constraint quiz_questions_type_check
            check ((type)::text = ANY
                   ((ARRAY ['MULTIPLE_CHOICE'::character varying, 'TRUE_FALSE'::character varying, 'SHORT_ANSWER'::character varying])::text[])),
    quiz_id bigint       not null
        constraint fkhflh2hxb7oik494car5w2px7x
            references posts
);

create table quiz_question_correct_answers
(
    question_id   bigint  not null
        constraint fk1dgp1q7692q1h2vu9ix64gmw7
            references quiz_questions,
    correct_index integer not null
);

create table quiz_question_options
(
    question_id  bigint       not null
        constraint fkkl6tbgdyegw1o9agywy1xje60
            references quiz_questions,
    option_text  varchar(255) not null,
    option_index integer      not null,
    primary key (question_id, option_index)
);

create table students
(
    address       varchar(255),
    faculty       varchar(255),
    program       varchar(255),
    year_of_study varchar(255),
    user_id       bigint not null
        primary key
        constraint fkdt1cjx5ve5bdabmuuf3ibrwaq
            references users
);

create table enrollments
(
    id          bigint generated by default as identity
        primary key,
    enrolled_at timestamp(6),
    final_grade varchar(2),
    final_score numeric(5, 2),
    status      varchar(255) not null
        constraint enrollments_status_check
            check ((status)::text = ANY
                   ((ARRAY ['ENROLLED'::character varying, 'DROPPED'::character varying])::text[])),
    course_id   bigint       not null
        constraint fkho8mcicp4196ebpltdn9wl6co
            references courses,
    student_id  bigint       not null
        constraint fk8kf1u1857xgo56xbfmnif2c51
            references students,
    constraint uk_student_course
        unique (student_id, course_id)
);

create table enrollment_sessions
(
    enrollment_id bigint not null
        constraint fk84j5ciq1347lumqkw9y72mg4m
            references enrollments,
    session_id    bigint not null
        constraint fktu82wfx4t0xyf1vxucv9c89m
            references course_sessions,
    primary key (enrollment_id, session_id)
);

create table submissions
(
    id                 bigint generated by default as identity
        primary key,
    graded_at          timestamp(6),
    professor_feedback text,
    score              numeric(5, 2),
    submitted_at       timestamp(6),
    post_id            bigint not null
        constraint fk7nsknt872tjj5javswcv8g01s
            references posts,
    student_id         bigint not null
        constraint fkhwebuw14r6lb2ja85w9mwa8vf
            references students,
    constraint uk_student_assignment
        unique (student_id, post_id)
);

create table quiz_answers
(
    id             bigint generated by default as identity
        primary key,
    awarded_points integer,
    provided_text  text,
    question_id    bigint not null
        constraint fkb69mwpkm3kehim0klscpmmkc1
            references quiz_questions,
    submission_id  bigint not null
        constraint fkhx978r5dxffj2y3unkyqylcmm
            references submissions,
    constraint uk_submission_question
        unique (submission_id, question_id)
);

create table quiz_answer_selections
(
    answer_id      bigint  not null
        constraint fkponuia50oo56yi3qxepgccpr0
            references quiz_answers,
    selected_index integer not null
);

create table submission_attachments
(
    submission_id bigint not null
        constraint fk1eg2nxu5gwqrtxp020uydj1q6
            references submissions,
    attachment_id bigint not null
        constraint ukkj80w1gafbq2owhxqi5o37d7b
            unique
        constraint fkixsp3wjd48t59fqexl2tnjut9
            references attachments,
    primary key (submission_id, attachment_id)
);
